title: Digits Semantic UI
description: Allows the creation, editing, and listing of contacts given in a database.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions